ublaboo -> contributte (#1067)
contributte/datagrid pull request #1075
Opened 2023-04-15 01:13 UTC by lilianalillyy

Renames namespace from `Ublaboo\DataGrid` to `Contributte\Datagrid`  (issue #1067) - package name not yet changed. 

Script that generates compatibility.php: https://gist.github.com/lilianalillyy/ee8de66b416fd1d680c58eba3f641d15

2023-04-16 06:24 UTC, radimvaculik commented
@lilianalillyy Thanks for PR! 🎉 Could you make CI green, please?

2023-04-16 12:25 UTC, lilianalillyy commented
This should be everything, the only things that have been left intentionally

1. `ublaboo/datagrid` library name (Composer) and `ublaboo-datagrid` (NPM) - This I'm leaving to @f3l1x / @paveljanda, who have to publish new packages (imo, the current packages should be deprecated though not removed completely, with a deprecation notice to use `contributte/datagrid`/`@contributte/datagrid` instead (both managers support this, even with the ability of referencing which package should be used as replacement). (Affected files: .docs/index,filters,assets.md, .docs/assets.md, README.md, package.json, composer.json)
2. CSS/JS assets - those are both subject to change already (rewrite)

As for translation keys, they are now prefixed with `contributte_`, rest stays the same. Before, they used the `ublaboo_` prefix, which will still function and will be automatically transformed to the contributte_ equivalent (a E_USER_DEPRECATED error will be triggered for the ublaboo_ keys). Implementation of that can be seen in SimpleTranslator.php.

2023-04-18 09:54 UTC, radimvaculik commented
@lilianalillyy Could you make CI green, please?

2023-04-18 10:00 UTC, lilianalillyy commented
`PHP Fatal error:  Declaration of Contributte\Datagrid\Filter\SubmitButton::getControl(object|string|null $caption = null): Nette\Utils\Html must be compatible with Nette\Forms\Controls\Button::getControl($caption = null): Nette\Utils\Html in /home/runner/work/datagrid/datagrid/src/Filter/SubmitButton.php on line 34`

It doesn't make sense to me, for reference:
```php
<?php
// ...
use Nette\Utils\Html;

// ...

public function getControl(string|object|null $caption = null): Html
{
 // ...
}
```

2023-04-18 10:03 UTC, radimvaculik commented
Does it fail on your local, when `make cs` ?

2023-04-18 10:10 UTC, lilianalillyy commented
nope, I only had an issue with the alphabetical sorting (which I've now fixed), this error didn't occur

2023-04-18 10:14 UTC, radimvaculik commented
I just clone your repo, run `make` and `make cs` and got the error. Running on PHP 8.0 locally.

2023-04-18 10:22 UTC, lilianalillyy commented
Removing vendor and reinstalling dependencies caused the same issue, however I fail to see how this PR affected that

2023-04-18 10:23 UTC, radimvaculik commented
Is `compatibility.php` included in phpcs/phpstan paths somehow?

2023-04-18 10:27 UTC, lilianalillyy commented
it's included in the composer autoload, however I doubt it has any impact on this as the error is regarding a Contributte namespace, and looking closely I see the issue, just not sure how it passed the CI before

2023-04-18 10:33 UTC, lilianalillyy commented
It shouldn't work in the first place, as the signature of the parent class is in fact different

2023-04-18 10:34 UTC, radimvaculik commented
But if you clone original repo, run `make` and `make cs`, it works like a charm 🤷‍♂️

2023-04-18 10:38 UTC, lilianalillyy commented
i believe it's some sort of a bug: repro:
cs doesn't work on my next branch -> checkout to d7bbdacb738565bf0adef37059b179c33104fa0f (last commit of contributte's next branch -> make cs works -> checkout to e7b9b5e9907489512b6f35747a5208293d5b8b6e (last commit of my next branch) -> make cs works now

2023-04-19 09:35 UTC, lilianalillyy commented
I have no idea what causes this, if someone could take a look it'd be great?

2023-04-20 11:19 UTC, lilianalillyy commented
It's already shared in a gist above ^

2023-04-20 18:14 UTC, radimvaculik commented
@lilianalillyy Let's go with for now.

```
-       public function getControl(string|object|null $caption = null): Html
+       /** @inheritDoc */
+       public function getControl($caption = null): Html
```

2023-04-20 18:15 UTC, lilianalillyy commented
sounds good, let me update the code

2023-04-20 18:19 UTC, radimvaculik requested changes

2023-04-20 18:19 UTC, radimvaculik commented on src/Localization/SimpleTranslator.php
> +					trigger_error(`Translation key '$key' is deprecated, please use '$newKey' instead`, E_USER_DEPRECATED);
@lilianalillyy Use `sprintf`

2023-04-20 18:26 UTC, radimvaculik commented
@f3l1x @paveljanda All good to me. Could you check PR and eventually merge it? Thanks guys.

2023-04-20 18:27 UTC, radimvaculik approved these changes

2023-05-06 15:27 UTC, radimvaculik commented
@lilianalillyy Please, rebase 🙈

2023-05-06 15:33 UTC, lilianalillyy commented
Will get to it later today!

2023-05-08 10:56 UTC, lilianalillyy commented
@radimvaculik rebased! sorry it took so long, i was out of town (Brno :D)

2023-05-08 13:19 UTC, merged

2023-05-08 13:19 UTC, radimvaculik commented
@lilianalillyy Thanks for contributing 👍