Datepicker input
contributte/datagrid pull request #1096
Opened 2023-08-21 15:43 UTC by MartinKokesCz

Based on issue #946 I have prepared the simple HTML input type="date" for date and date range filter.

You can try it with my fork of datagrid-skeleton

https://github.com/MartinKokesCz/datagrid-skeleton/tree/next

2023-08-22 07:08 UTC, radimvaculik commented
@MartinKokesCz Please check Phpstan issues related to changes. I will fix the rest of codesniffer/phpstan issues.

2023-08-22 07:48 UTC, radimvaculik commented
@MartinKokesCz Please, rebase, I fixed all related issues in `next` branch.

2023-08-22 09:00 UTC, MartinKokesCz commented
@radimvaculik maybe it is ready now ?

2023-08-30 09:50 UTC, radimvaculik requested changes

2023-08-30 09:50 UTC, radimvaculik commented on src/Column/ColumnDateTime.php
> +	public function getFormat(): string
No need anymore. @MartinKokesCz

2023-08-31 06:24 UTC, MartinKokesCz commented on src/Column/ColumnDateTime.php
> +	public function getFormat(): string
@radimvaculik ok, removed. Thanks

2024-04-15 11:08 UTC, closed without merging